cart/urls.py
from django.contrib import admin
from .views import *
from django.urls import path

app_name = 'cart'
urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name="product_add"),
    path('remove/<int:product_id>/', remove, name="product_remove"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('support/', include('support.urls')),
    path('',  include('shop.urls')),
]

shop/urls.py
from django.contrib import admin
from .views import *
from django.urls import path

app_name = 'shop'
urlpatterns = [
    path('', product_in_category, name="product_all"),
    path('sort/<slug:sort_slug>/', sort_in_slug, name="sort_in_slug"),
    path('category/<slug:category_slug>/',
         product_in_category, name="product_in_category"),
    path('<int:id>/<product_slug>/', product_detail,
         name="product_detail"),
    path('search', search_bar, name='search'),
    path('filter',
         filter, name='filter2'),
    path('filter2', FilterAjaxView.as_view(), name='filter_ajax'),
    path('put/<int:id>', put_into_wishlist, name='put_into_wishlist'),
    path('wishlist/', wishlist, name='wishlist'),
    path('remove/<int:id>', remove_from_wishlist, name='remove_from_wishlist'),
    path('create_support', create_support, name='create_support'),
    path('supportlist/', supportlist, name='supportlist'),
    path('paypal/<str:order>', paypal, name='paypal'),
    path('redirect/', redirect, name='redirect'),
    path('completeOrder', completeOrder, name='completeOrder'),
    path('review_write/<int:product_id>', review_write, name='review_write'),
    path('create_review', create_review, name='create_review'),
    path('review_detail/<int:review_id>', review_detail, name='review_detail'),
    path('support_detail/<int:support_id>',
         support_detail, name='support_detail'),
    path('orders',
         orders, name='orders'),
    path('settings',
         settings, name='settings'),

]

templates/base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css2?family=Karla:wght@200&display=swap" rel="stylesheet">



{% block script %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block style %}
{% endblock %}
</head>

<body>
<nav class="navbar sticky-top navbar-expand-sm navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Django Ecommerce</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mt-2 mt-l">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:create_support' %}">Support</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:detail' %}">Cart
          {% if cart|length > 1 %}
                ${{cart.get_product_total}} with {{cart|length}} items
          {% elif cart|length == 1%}
                ${{cart.get_product_total}} with {{cart|length}} item
          {% else %}
                : Empty
          {% endif %}
          </a>
        </li>
      </ul>
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        My Page
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'cart:detail' %}">My Cart</a>
          <a class="dropdown-item" href="{% url 'shop:orders' %}">My Orders</a>
          <a class="dropdown-item" href="{% url 'shop:wishlist' %}">My Wish List</a>
          <a class="dropdown-item" href="{% url 'shop:supportlist' %}">My Supports</a>
          <a class="dropdown-item" href="{% url 'shop:settings' %}">Change Password</a>
          <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
        </div>
      </div>
      <form class="form-inline my-2 my-lg-0" action = "{% url 'shop:search' %}">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name = "q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      </div>
    </div>
  </div>
</nav>
<div class = "container">
  {% block content %}
  {% endblock %}
</div>





</body>
</html>