cart/urls.py
from django.contrib import admin
from .views import *
from django.urls import path

app_name = 'cart'
urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name="product_add"),
    path('remove/<int:product_id>/', remove, name="product_remove"),
]

order/urls.py
from django.urls import path, include
from .views import *
app_name = "order"
urlpatterns = [
    path('create/', order_create, name="order_create"),
    path('create/ajax', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
    path('order_detail/<int:order_id>/',
         admin_order_detail, name='admin_order_detail'),
]

shop/urls.py
from django.contrib import admin
from .views import *
from django.urls import path

app_name = 'shop'
urlpatterns = [
    path('', product_in_category, name="product_all"),
    path('sort/<slug:sort_slug>/', sort_in_slug, name="sort_in_slug"),
    path('category/<slug:category_slug>/',
         product_in_category, name="product_in_category"),
    path('<int:id>/<product_slug>/', product_detail,
         name="product_detail"),
    path('search', search_bar, name='search'),
    path('filter',
         filter, name='filter2'),
    path('filter2', FilterAjaxView.as_view(), name='filter_ajax'),
    path('put/<int:id>', put_into_wishlist, name='put_into_wishlist'),
    path('wishlist/', wishlist, name='wishlist'),
    path('remove/<int:id>', remove_from_wishlist, name='remove_from_wishlist'),
    path('create_support', create_support, name='create_support'),
    path('supportlist/', supportlist, name='supportlist'),
    path('paypal/<str:order>', paypal, name='paypal'),
    path('redirect/', redirect, name='redirect'),
    path('completeOrder', completeOrder, name='completeOrder'),
    path('review_write/<int:product_id>', review_write, name='review_write'),
    path('create_review', create_review, name='create_review'),
    path('review_detail/<int:review_id>', review_detail, name='review_detail'),
    path('support_detail/<int:support_id>',
         support_detail, name='support_detail'),
    path('orders',
         orders, name='orders'),
    path('settings',
         settings, name='settings'),

]

support/urls.py
from django.contrib import admin
from .views import *
from django.urls import path
from .views import *

app_name = 'support'
urlpatterns = [
    path('', support_create, name="create"),
]

support/models.py
from django.db.models.signals import post_save
import hashlib
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from coupon.models import Coupon
from shop.models import Product
from django.contrib.auth.models import User

order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['author', 'first_name', 'last_name', 'email', 'address', 'postal_code',
                  'city']

support/forms.py
from django import forms

order/views.py
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic.base import View
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.cart import Cart
from .forms import *
# Create your views here.


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        # 입력받은 정보를 후처리
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            if cart.coupon:
                order.coupon = cart.coupon
                # order.discount = cart.coupon.amount
                order.discount = cart.get_discount_total()
                order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            total = cart.get_product_total()
            cart.clear()
            return render(request, 'shop/paypal.html', {'order': order, 'total': total})
    else:
        form = OrderCreateForm(initial={'author': request.user})
    return render(request, 'order/create.html', {'cart': cart, 'form': form})
# JS 동작하지 않는 환경에서도 주문은 가능해야한다. : order_create의 용도


def order_complete(request):
    order_id = request.GET.get('order_id')
    # order = Order.objects.get(id=order_id)
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/created.html', {'order': order})


class OrderCreateAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        cart = Cart(request)
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.get_discount_total()
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            total = cart.get_product_total()
            cart.clear()
            data = {
                "order_id": order.id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


class OrderCheckoutAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get('order_id')

        order = Order.objects.get(id=order_id)
        amount = request.POST.get('amount')

        try:
            # mechant_order_id : OrderTransaction object
            merchant_order_id = OrderTransaction.objects.create_new(
                order=order,
                amount=amount
            )
        except:
            merchant_order_id = None

        if merchant_order_id is not None:
            data = {
                "works": True,
                "merchant_id": merchant_order_id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


class OrderImpAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)

        merchant_id = request.POST.get('merchant_id')
        imp_id = request.POST.get('imp_id')
        amount = request.POST.get('amount')

        try:
            trans = OrderTransaction.objects.get(
                order=order,
                merchant_order_id=merchant_id,
                amount=amount
            )
        except:
            trans = None

        if trans is not None:
            trans.transaction_id = imp_id
            # trans.success = True
            trans.save()
            order.paid = True
            order.save()

            data = {
                "works": True
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/admin/detail.html', {'order': order})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core import serializers


# Create your views here.
from .models import *
from .forms import *
from cart.forms import AddProductForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic.base import View
from django.http import JsonResponse
from django.db.models.query import EmptyQuerySet
from order.models import *
import json
from django.http import HttpResponse, HttpResponseRedirect
from decimal import Decimal
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect


@login_required
def settings(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'shop/settings.html', {
        'form': form
    })


@login_required
def orders(request):
    user = request.user
    orders = Order.objects.filter(author=user)
    return render(request, 'shop/orders.html', {'orders': orders})


def support_detail(request, support_id):
    support = Support.objects.get(id=support_id)
    return render(request, 'shop/support_detail.html', {'support': support})


def review_detail(request, review_id):
    review = Review.objects.get(id=review_id)
    return render(request, 'shop/review_detail.html', {'review': review})


def create_review(request):
    form = ReviewForm(request.POST)
    if form.is_valid():
        review = form.save()
        return JsonResponse({})


def review_write(request, product_id):
    product = Product.objects.get(id=product_id)
    form = ReviewForm(initial={'author': request.user,
                               'product': product, 'stars': 5})
    return render(request, 'shop/review_write.html', {'form': form})


def completeOrder(request):
    if request.is_ajax():
        id = request.POST.get('order_id')
        order = Order.objects.get(id=id)
        order.paid = True
        order.save()
        return JsonResponse({'url': reverse('shop:product_all')})
    else:
        return JsonResponse({}, status=401)


def redirect(request):
    if request.is_ajax():
        order_transaction = request.POST.get('merchant_id')
        order_transaction = OrderTransaction.objects.get(id=order_transaction)
        order = order_transaction

        return JsonResponse({
            'url': reverse('shop:paypal', args=[order.id])
        })
    else:
        return JsonResponse({}, status=401)


def paypal(request, order):
    order_transaction = request.POST.get('merchant_id')
    order_transaction = OrderTransaction.objects.get(id=order)
    amount = order_transaction.amount
    order = order_transaction.order

    return render(request, 'shop/paypal.html', {'order': order, 'amount': amount})


@login_required
def supportlist(request):
    supportlist = SupportList.objects.get(
        user=request.user)
    supportlist = supportlist.supports.all()
    return render(request, 'shop/supportlist.html', {'supportlist': supportlist})


@login_required
def create_support(request):
    if request.method == 'POST':
        # 입력받은 정보를 후처리
        form = SupportCreateForm(request.POST)
        if form.is_valid():
            support = form.save()
            supportlist = SupportList.objects.get(
                user=request.user)  # wishlist was never made
            supportlist.supports.add(support)
            supportlist = supportlist.supports.all()
            return render(request, 'shop/supportlist.html', {'supportlist': supportlist})
    else:
        form = SupportCreateForm(initial={'author': request.user})
    return render(request, "shop/support.html", {"form": form})


@login_required
def remove_from_wishlist(request, id):
    wishlist = WishList.objects.get(
        user=request.user)
    product = get_object_or_404(Product, id=id)
    wishlist.items.remove(product)
    wishlist = wishlist.items.all()
    return render(request, 'shop/wishlist.html', {'wishlist': wishlist})


@login_required
def wishlist(request):
    wishlist = WishList.objects.get(
        user=request.user)
    wishlist = wishlist.items.all()
    return render(request, 'shop/wishlist.html', {'wishlist': wishlist})


@login_required
def put_into_wishlist(request, id):
    wishlist = WishList.objects.get(
        user=request.user)  # wishlist was never made
    wishlist.items.add(Product.objects.get(id=id))
    product = get_object_or_404(Product, id=id)
    add_to_cart = AddProductForm(initial={'quantity': 1})
    reviews = Review.objects.filter(product__id=id)
    return render(request, 'shop/detail.html', {'product': product, 'add_to_cart': add_to_cart, 'reviews': reviews})


def sort_in_slug(request, sort_slug=None):
    sorts = Sorted.objects.all()
    if request.session['current_category'] == "":
        current_category = None
    else:
        current_category = Category.objects.get(
            id=request.session['current_category'])
    categories = Category.objects.all()
    products = Product.objects.filter(
        pk__in=request.session['display_queryset'])
    if sort_slug:
        current_sort = get_object_or_404(Sorted, slug=sort_slug)
        request.session['current_sort'] = current_sort.id
    slug = current_sort.slug
    if (slug == "alphabetically"):
        products = products.order_by("name")
    elif (slug == "price-high-low"):
        products = products.order_by("-price")
    elif (slug == "price-low-high"):
        products = products.order_by("price")
    elif (slug == "recent"):
        products = products.order_by("-created")
    else:
        products = products.order_by("-view")
    temp = helper(products)
    brands = temp[0]
    sizes = temp[1]
    colors = temp[2]
    prices = temp[3]
    return render(request, 'shop/list.html', {'current_sort': current_sort,
                                              'current_category': current_category,
                                              'sorts': sorts,
                                              'categories': categories,
                                              'products': products, 'brands': brands, 'sizes': sizes,
                                              'colors': colors, 'prices': prices})


@login_required
def product_in_category(request, category_slug=None):
    if 'current_sort' not in request.session:
        request.session['current_sort'] = ""
    current_user = request.user
    wishlist = WishList.objects.filter(
        user=current_user)
    if len(wishlist) == 0:
        new_wishlist = WishList(
            user=current_user)
        new_wishlist.save()

    supportlist = SupportList.objects.filter(
        user=current_user)
    if len(supportlist) == 0:
        new_supportlist = SupportList(
            user=current_user)
        new_supportlist.save()

    current_category = None
    categories = Category.objects.all()
    sorts = Sorted.objects.all()
    products = Product.objects.filter(available_display=True)
    temp = helper(products)
    brands = temp[0]
    sizes = temp[1]
    colors = temp[2]
    prices = temp[3]
    display = [product.id for product in products]
    request.session['display_queryset'] = display
    request.session['current_category'] = ""
    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)
        display = [product.id for product in products]
        request.session['display_queryset'] = display
        request.session['current_category'] = current_category.id
        all_products = False
    else:
        all_products = True
    return render(request, 'shop/list.html', {'current_category': current_category,
                                              'categories': categories,
                                              'products': products, 'brands': brands, 'sizes': sizes,
                                              'colors': colors, 'prices': prices, 'sorts': sorts, 'all_products': all_products})


def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id)
    add_to_cart = AddProductForm(initial={'quantity': 1})
    reviews = Review.objects.filter(product__id=id)
    return render(request, 'shop/detail.html',
                  {'product': product, 'add_to_cart': add_to_cart, 'reviews': reviews})


def search_bar(request):
    try:
        q = request.GET.get('q')
    except:
        q = None

    queryset = []
    categories = Category.objects.all()
    current_category = None
    sorts = Sorted.objects.all()
    if q:
        template = "shop/search.html"
        split = q.split()
        for word in split:
            products = Product.objects.filter(Q(brand__icontains=word) |
                                              Q(name__icontains=word) |
                                              Q(description__icontains=word)).distinct()
            for product in products:
                queryset.append(product)
        display = [product.id for product in queryset]
        request.session['display_queryset'] = display
        request.session['current_category'] = ""
    else:
        template = "shop/list.html"
        queryset = None
        display = []
        request.session['current_category'] = ""

    return render(request, template, {"queryset": queryset, "categories": categories, "current_category": current_category, "sorts": sorts})

shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block title %} {{product.name}} {% endblock%}
{% block content%}
    <div class = "row">
        <div class = "col-4">
            <img src = "{{product.image.url}}" width = "100%">
        </div>
        <div class = "col">
            <h1 class = "display-6">{{product.name}}</h1>
            <h5><span class = 'badge badge-secondary'>Brand</span>
            {{product.brand}}</h5>
            <h5><span class = 'badge badge-secondary'>Price</span>
            ${{product.price}}</h5>
            <h5><span class = 'badge badge-secondary'>Size</span>
            {{product.size}}</h5>
            <h5><span class = 'badge badge-secondary'>Description</span>{{product.description|linebreaks}}</h5>
            <h5><span class = 'badge badge-secondary'>Details</span>{{product.details|linebreaks}}</h5>
            <h5><span class = 'badge badge-secondary'>Size and Fits</span>{{product.size_and_fits|linebreaks}}</h5>
            <h5><span class = 'badge badge-secondary'>Reviews</span></h5>
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">User Name</th>
                        <th scope="col">Stars</th>
                    </tr>
                </thead>
                <tbody>
                    {% for review in reviews %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td><a href = "{% url 'shop:review_detail' review.id %}">{{review.title}}</td>
                        <td>{{review.author}}</td>
                        <td>{{review.stars}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <a href = "{{product.put_into_wishlist}}" class="btn btn-outline-danger my-2 my-sm-0">Like</a>
            <button type = "submit" onclick = "location.href='{% url 'shop:review_write' product.id %}'" class = "btn btn-outline-primary my-2 my-sm-0"  style="float: right;">Write a Review</button>
            </br>
            </br>
            <form action ="{% url 'cart:product_add' product.id %}" method = "post">
                {{add_to_cart}}
                {% csrf_token %}
                <input type = "submit" class = "btn btn-outline-primary my-2 my-sm-0" value = "Add to Cart">
            </form>
        </div>
    </div>
{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}Django Ecommerce{% endblock %}
{% block script %}
<script type="text/javascript">
    csrf_token = '{{csrf_token}}';
    filter_url = '{% url "shop:filter_ajax" %}';
    
</script>
{% load static %}
<script src="{% static 'js/filter.js' %}" type="text/javascript"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<div class = "row">
    <div class = "col-2">
        <div class = "list-group">
            <a href = "/" id = "overwrite_test" class = "list-group-item {% if all_products == True %} active
            {% endif %}"> All </a>
            {% for c in categories %}
            <a href = "{{c.get_absolute_url}}" class = "list-group-item {% if current_category.slug == c.slug %} active
            {% endif %}">{{c.name}}</a>
            {% endfor %}
        </div>
        </br>
        <ul class = "list-group">
            <a href = "/" class = "list-group-item {% if current_sort.slug == sort.slug %} active {% endif %}"> Sort By </a>
            {% for sort in sorts %}
            <a href = "{{sort.get_absolute_url}}" class = "list-group-item {% if current_sort.slug == sort.slug %} active
            {% endif %}">{{sort.name}}</a>
            {% endfor %}
            
        </ul>
        </br>
        <ul class = "list-group">
        <a href = "/" class = "list-group-item active"> Filter By </a>
        <form method = "post" class="filter-form">
        {% csrf_token %}
            <div class="form-group">
                <select id = "color" class="custom-select">
                    <option selected>Color</option>
                    {% for color in colors %}
                    <option value="{{color}}"">{{color}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <select id = "price" class="custom-select">
                    <option selected>Price Range</option>
                    {% for price in prices %}
                    <option value="{{price}}">{{price}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <select id = "size" class="custom-select">
                    <option selected>Size</option>
                    {% for size in sizes %}
                    <option value="{{size}}">{{size}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <select id = "brand" class="custom-select">
                    <option selected>Brand</option>
                    {% for brand in brands %}
                    <option value="{{brand}}">{{brand}}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </ul>
    </div>
    <div class = "col">
        <div class = "alert alert-info">
            {% if current_category %}
            {{current_category.name}}
            {% else %}All Products
            {% endif %}
        </div>
        <div class = "row">
            {% for product in products %}
            <div class = "col-4">
                <div class = "card"> 
                    <img class = "cart-img-top" src = "{{product.image.url}}" alt = "Product Image" style="width: 100%">
                    <div class = "card-body">
                        <h5 class = "card-title">{{product.name}}</h5>
                        <h5 class = "card-brand">{{product.brand}}</h5>
                        <p class = "card-text">{{product.description}}</p>
                        <div class = "badge badge-secondary">Price</div> ${{product.price}}</p>
                        <div class = "badge badge-secondary">Size</div> {{product.size}}</p>
                        <a href = "{{product.put_into_wishlist}}" class="btn btn-outline-danger my-2 my-sm-0">Like</a>
                        <a href = "{{product.get_absolute_url}}" class = "btn btn-outline-primary my-2 my-sm-0">View Detail</a>
                    </div>
                </div>
            </div>
            {% endfor %}
    </div>

{% endblock content %}

shop/templates/shop/paypal.html
{% extends 'base.html' %}
{% block title %}Payment{% endblock %}
{% block script %}
<script src="https://www.paypal.com/sdk/js?client-id=AbUFYLPf8ImNIsy5e6I-b0lklHhBXa18ygNba0KdpJDGdhrNeqpgfImQ-Y4rw4fkwGZom9kVw-UHPJa-&currency=USD"></script>
{% endblock %}

{% block content %}
<div class = "alert alert-info">
           Please use paypal to make a payment for your order
</div>
<div class = "alert alert-info">
           This website is a demo ecommerce website and does not support real 
           Paypal service. It still supports paying with a sandbox paypal account. 
</div>
<div id="paypal-button-container"></div>
<script src="https://www.paypal.com/sdk/js?client-id=AbUFYLPf8ImNIsy5e6I-b0lklHhBXa18ygNba0KdpJDGdhrNeqpgfImQ-Y4rw4fkwGZom9kVw-UHPJa-&currency=USD&disable-funding=credit"></script>
<script>
        var total = '{{amount}}'
        var order_id = '{{order.id}}'
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        function completeOrder(){

            var url = "{% url 'shop:completeOrder' %}"
            var request = $.ajax({
                method: "POST",
                url: url,
                async: false,
                data: {
                    order_id: order_id,
                    csrfmiddlewaretoken: csrftoken
                }
            });
            request.done(function (data) {
                window.location.href = data.url;
        });
        }
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
            style: {
                color: 'blue',
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: total
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    completeOrder()
                });
            }


        }).render('#paypal-button-container');
    </script>
{% endblock %}

shop/templates/shop/review_detail.html
{% extends 'base.html' %}
{% block title %} Review Detail{% endblock%}

{% block content%}
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">Review Detail</div>
    </div>
</div>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{review.title}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Written By {{review.author}}</h6>
    <h6 class="card-subtitle mb-2 text-muted">{{review.created}}</h6>
    <p class="card-text">{{review.description}}</p>
  </div>
</div>
{% endblock%} 

shop/templates/shop/review_write.html
{% extends 'base.html' %}
{% block title %} Review  {% endblock%}
{% block script %}
<script type="text/javascript">
    csrf_token = '{{csrf_token}}';
    review_create_url = '{% url "shop:create_review" %}';
</script>
{% load static %}
<script src="{% static 'js/review.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content%}
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">Please fill out the review below.</div>
        <form action="" method="post" class="review-form">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary float-right" value="Submit a Review">
        </form>
    </div>
</div>
{% endblock%} 

shop/templates/shop/settings.html
{% extends 'base.html' %}
{% block title %}Settings{% endblock %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

shop/templates/shop/support.html
{% extends 'base.html' %}

{% block title %}
Support
{% endblock %}

{% block script %}
<script type="text/javascript">
    csrf_token = '{{csrf_token}}';
    support_create_url = '{% url "shop:create_support" %}';
</script>
{% load static %}
<script src="{% static 'js/support.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">Please fill out the form below correctly for a response from us. We will get back to you as soon as possible.</div>
        <form action="" method="post" class="support-form">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary float-right" value="Submit a query">
        </form>
    </div>
</div>
{% endblock %}

shop/templates/shop/supportlist.html
{% extends 'base.html' %}
{% block title %}
Support List
{% endblock %}
{% block content %}
<div class = "row">
<div class = "col">
        <div class = "alert alert-info">
            {% if current_category %}
            {{current_category.name}}
            {% else %}Your support list
            {% endif %}
        </div>
        <div class = "row">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Product</th>
                        <th scope="col">Content</th>
                        <th scope="col">Submitted</th>
                    </tr>
                </thead>
                <tbody>
                    {% for support in supportlist %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td><a href = "{% url 'shop:support_detail' support.id %}">{{support.product}}</td>
                        <td>{{support.query}}</td>
                        <td>{{support.created}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}