cart/urls.py
from django.contrib import admin
from .views import *
from django.urls import path

app_name = 'cart'
urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name="product_add"),
    path('remove/<int:product_id>/', remove, name="product_remove"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('support/', include('support.urls')),
    path('',  include('shop.urls')),
]

support/urls.py
from django.contrib import admin
from .views import *
from django.urls import path
from .views import *

app_name = 'support'
urlpatterns = [
    path('', support_create, name="create"),
]

support/models.py
from django.db.models.signals import post_save
import hashlib
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from coupon.models import Coupon
from shop.models import Product
from django.contrib.auth.models import User

support/forms.py
from django import forms

support/views.py
from django.shortcuts import render
from .forms import *
from .models import *
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic.base import View
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
# Create your views here.


def support_create(request):
    if request.method == 'POST':
        # 입력받은 정보를 후처리
        form = SupportCreateForm(request.POST)
        if form.is_valid():
            support = form.save()
            return render(request, 'support/created.html', {'support': support})
    else:
        form = SupportCreateForm()
    return render(request, "support/support.html", {"form": form})


class SupportCreateAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        form = SupportCreateForm(request.POST)
        if form.is_valid():
            support = form.save(commit=False)
            data = {
                "support_id": support.id
            }
            support.save()
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)

support/templates/support/support.html
{% extends 'base.html' %}

{% block title %}
Checkout
{% endblock %}

{% block script %}
<script type="text/javascript">
    csrf_token = '{{csrf_token}}';
    support_create_url = '{% url "support:create" %}';
</script>
{% load static %}
<script src="{% static 'js/support.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">Please fill out the form below correctly for a response from us. We will get back to you as soon as possible.</div>
        <form action="" method="post" class="support-form">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary float-right" value="Submit a query">
        </form>
    </div>
</div>
{% endblock %}